<?php

use Drupal\file\Entity\File;

/**
 * @file
 * Contains custom_design.module.
 */

function custom_design_preprocess_page(&$variables) {
  _custom_design_preprocess_var($variables);
}

function custom_design_preprocess_html(&$variables) {
  _custom_design_preprocess_var($variables);
}

function _custom_design_preprocess_var(&$variables) {
  $config = \Drupal::service('config.factory')->getEditable('custom_design.settings');

  if ($fid = $config->get('fid')) {
    $file = File::load($fid);
    $uri = $file->getFileUri();
    $url = file_create_url($uri);
    $variables['custom_bg_image'] = ' style="background: url(\''. $url .'\') center no-repeat"';
  }

}
