<?php

use Drupal\file\Entity\File;

/**
 * @file
 * Contains custom_design.module.
 */

function custom_design_preprocess_page(&$variables) {
  _custom_design_preprocess_var($variables);
}

function custom_design_preprocess_html(&$variables) {
  _custom_design_preprocess_var($variables);
}

function _custom_design_preprocess_var(&$variables) {
  $config = \Drupal::service('config.factory')->getEditable('custom_design.settings');

  $type = $config->get('type');
  $fid = $config->get('fid');

  if ($type && $fid) {
    $file = File::load($fid);
    $uri = $file->getFileUri();
    $url = \Drupal::service('file_url_generator')->generateAbsoluteString($uri);

    $variables['custom_bg_type'] = $type;
    $variables['custom_bg_url'] = $url;
  }
}
